# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: decabe4cea22141f524e4398f9dd919aa18d0915ee6953cb837a1053c5c490b613837b8ef4fc1e51a5273a102de5142aa454e71adca7efde60a41acefae66c8a

test:
  secret_key_base: cd051a85f261fcb1f1feb98286fa4059e484e3402941e928dd4287a39c45a1dfe40a9700fbb12d761f1c4b9756813ddd0c1296fa65792efc90cb7bd904502978

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
